repos:
  - repo: local
    hooks:
      - id: clean
        name: Making sure you cleaned up the notebooks
        entry: nbdev_clean
        language: system
        always_run: true
        pass_filenames: false
      - id: docs
        name: Making sure you generated the docs
        entry: nbdev_docs
        language: system
        always_run: true
        pass_filenames: false