# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tinygrad-notes',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/tinygrad-notes',
                'lib_path': 'tinygrad_notes'},
  'syms': {'tinygrad_notes.core': {'tinygrad_notes.core.foo': ('core.html#foo', 'tinygrad_notes/core.py')}}}
